version: '3'

services:
  api:
    build: .
    command: sh -c "uvicorn api_rag:app --reload --port:8080 --host:0.0.0.0"
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app

